# 
#   Copyright (C) 1995 Free Software Foundation
#   Written by Michael I. Bushnell.
#
#   This file is part of the GNU Hurd.
#
#   The GNU Hurd is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2, or (at
#   your option) any later version.
#
#   The GNU Hurd is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

# Copyright (C) 1995 Free Software Foundation
# Escrito por Michael I. Bushnell.
#
# Este arquivo faz parte do GNU Hurd.
#
# O GNU Hurd é um software livre; você pode redistribuí-lo e / ou
# modifique-o sob os termos da GNU General Public License como
# publicado pela Free Software Foundation; ou versão 2, ou (em
# sua opção) qualquer versão posterior.
#
# O GNU Hurd é distribuído na esperança de que seja útil, mas
# SEM QUALQUER GARANTIA; sem mesmo a garantia implícita de
# COMERCIABILIDADE ou ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA. Veja o GNU
# Licença Pública Geral para mais detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa; se não, escreva para o Software Livre
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, EUA.

dir := login
makemode := misc

SRCS = utmp.c

include ../Makeconf
